name: dockerize

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && 'latest' || github.event.pull_request.number }}

jobs:
  build:
    name: Build Docker Image, Push to Container Registry
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.DOCKER_IMAGE_TAG }}
          build-args: |
            POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }}
